AutoFormat: false
FixParseErrors: true
Colors: true
PassCommandsToShell: true
WebInterface: false
Interactive: true
LogToFileColor: false
LogToFile: false
Debug: false
RecursionDepth: 1
ProjectNamePrompt: true
AllowUntypedArgs: false
ColorProfile: default
HistoryFile: true
HistoryLimit: 20
PortWebPanel: 8080
PortGlueServer: 0
ExitOnInterrupt: true
DisableTimestamps: false
PrintBuiltins: false
MakefileOverview: true
StopOnError: true
DumpScriptOnError: true
DateFormat: 02-01-2006
TodoFilePath: wiki/docs/TODO.md
