AutoFormat: false
FixParseErrors: true
Colors: true
PassCommandsToShell: true
WebInterface: false
Interactive: true
Debug: false
RecursionDepth: 1
ProjectNamePrompt: true
ColorProfile: default
HistoryFile: true
HistoryLimit: 20
PortWebPanel: 8080
PortGlueServer: 0
ExitOnInterrupt: true
DisableTimestamps: false
PrintBuiltins: false
MakefileOverview: false
StopOnError: true
DumpScriptOnError: true
DateFormat: 02.01.06
TodoFilePath: wiki/docs/TODO.md
rwmutex: {}
